name: Reusable workflow example

on:
  workflow_call:
    inputs:
      service_name:
        required: true
        type: string
      project_name:
        required: true
        type: string
    secrets:
      gce_sa_key:
        required: true
      project_id:
        required: true
      releases_secrets:
        required: true

jobs:
    setup_build_publish_deploy:
      runs-on: ubuntu-latest

      steps:
      - uses: google-github-actions/setup-gcloud@v0
        with:
          version: '290.0.1'
          service_account_key: ${{ secrets.gce_sa_key }}
          project_id: ${{ secrets.project_id }}

      # Configure Docker to use the gcloud command-line tool as a credential
      # helper for authentication
      - run: |-
          gcloud --quiet auth configure-docker


      - name: Checkout
        uses: actions/checkout@v2
      # Build the Docker image
      - name: Build
        run: |
          echo '${{ secrets.releases_secrets }}' >> config/releases.exs
          echo '${{ secrets.qna_answers }}' >> qna/answers.json
          echo '${{ secrets.courses_answers }}' >> courses/answers.json
          docker build --tag "gcr.io/duncan-openc2-plugfest/${{ inputs.project_name }}:$GITHUB_SHA" .

      # Push the Docker image to Google Container Registry
      - name: Publish
        run: |-
          docker push "gcr.io/duncan-openc2-plugfest/${{ inputs.project_name }}:$GITHUB_SHA"

      - name: Deploy
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          service: ${{ inputs.service_name }}
          region: us-east4
          tag: "${{ github.ref_name }}"
          image: "gcr.io/duncan-openc2-plugfest/${{ inputs.project_name }}:${{ github.sha }}"
